In [0]:
import numpy as np

# Numpy Basics

In [0]:
N=100000000

In [0]:
%%time
list1=list(range(N))
for i in range(N):
    list1[i]=list1[i]**2


CPU times: user 38.9 s, sys: 2.34 s, total: 41.2 s
Wall time: 41.3 s


In [0]:
%%time
list1=list(range(N))
list1=[item * item for item in list1]

CPU times: user 9.35 s, sys: 2.88 s, total: 12.2 s
Wall time: 12.2 s


In [0]:
%%time
list1=list(range(N))
list1=map(lambda x: x * x, list1)
list1[:10]

In [0]:
%%time
list1=list(range(N))
sumation=0
for item in list1:
    sumation+=item

CPU times: user 12 s, sys: 4.41 s, total: 16.4 s
Wall time: 16.4 s


In [0]:
%%time
list1=list(range(N))
sumation=sum(list1)

CPU times: user 3.31 s, sys: 1.57 s, total: 4.87 s
Wall time: 4.85 s


In [0]:
%%time
list1=np.arange(N)
list1=list1**2
print(list1[:10])

[ 0  1  4  9 16 25 36 49 64 81]
CPU times: user 430 ms, sys: 18.6 ms, total: 449 ms
Wall time: 450 ms


In [0]:
%%time
list1=np.arange(N)
summ=np.sum(list1)
print(summ)
print(list1)

4999999950000000
[       0        1        2 ... 99999997 99999998 99999999]
CPU times: user 285 ms, sys: 10 ms, total: 295 ms
Wall time: 302 ms


In [0]:
list2=[1,2,3,4]
list2[:]

[1, 2, 3, 4]

In [0]:
l1=[
    [1,2,3],
    [4,5,6]
]
l2=l1
l3=l1[:]
l4=list(l1[:])
l2[1][2]=10
print(l1,l2,l3,l4)

[[1, 2, 3], [4, 5, 10]] [[1, 2, 3], [4, 5, 10]] [[1, 2, 3], [4, 5, 10]] [[1, 2, 3], [4, 5, 10]]


In [0]:
a=np.array([1,2,3,4])

# Methods

In [0]:
a.size

4

In [0]:
a.shape

(4,)

In [0]:
a.nbytes

32

In [0]:
a.itemsize

8

In [0]:
a.dtype

dtype('int64')

In [0]:
arr1=np.ones((2,3,2),np.int64)

In [0]:
arr1.dtype

dtype('int64')

In [0]:
arr1.size

12

In [0]:
arr1.itemsize

8

In [0]:
arr1.shape

(2, 3, 2)

In [0]:
arr1.nbytes

96

In [0]:
arr1.ndim

3

In [0]:
np.random.randint(3,10,(2,3))

array([[6, 5, 3],
       [6, 4, 4]])

In [0]:
print(np.random.randn(100))

[ 2.38756409  1.14432304  0.60780664  1.65105512 -0.35364981  2.01766505
 -0.58590434 -1.26471698  0.98115312  1.06481201  1.52572374  1.00454718
 -0.25582004  0.28911106  0.97727734 -1.65338122 -1.04060831 -0.73046131
 -1.597932   -0.68611876  1.07790943  0.68528588  0.85811035 -0.26929746
  0.62508832 -0.9425073   0.06689282 -0.11050614 -1.09829829  1.60493791
  0.39079967  0.3921563  -0.20438758 -0.73194656 -0.5505141   0.74221621
  0.22256937 -1.42181263  0.55017398  1.37172201 -1.21456745 -1.16365561
  1.11978219  1.28964832  1.66134176  1.57569357  0.40039405  0.96571471
 -1.7024053  -1.92213638  0.49308688 -0.46591927  0.50416787 -0.03645015
 -1.81119552  0.62108886  0.27733808  0.20628606  0.19468165  0.60539392
  0.17895802  0.04433995  0.73540213  0.60867225  0.95546007  0.55768836
 -0.08134323 -0.97584018  1.04367703 -0.05050208  0.9268021  -0.11149313
 -1.19908285 -0.36742513 -1.06635496 -1.2063659   0.29704934 -0.46833971
  0.78255339 -1.82237469 -0.79096322  0.21820596 -1

In [0]:
np.random.rand(7,5)

array([[0.69236305, 0.30873178, 0.07937852, 0.14137488, 0.11568377],
       [0.92393252, 0.76770003, 0.72297907, 0.04159025, 0.44583641],
       [0.01379146, 0.39308219, 0.42288512, 0.61593085, 0.58566888],
       [0.68686581, 0.23966989, 0.95032156, 0.8911581 , 0.33706579],
       [0.91150009, 0.46343068, 0.3195563 , 0.84362256, 0.75118573],
       [0.41800329, 0.46213301, 0.95787807, 0.85092446, 0.06364575],
       [0.79197505, 0.24866292, 0.31419597, 0.32817062, 0.34964695]])

In [0]:
np.arange(150,step=7,dtype=np.int64)

array([  0,   7,  14,  21,  28,  35,  42,  49,  56,  63,  70,  77,  84,
        91,  98, 105, 112, 119, 126, 133, 140, 147])

In [0]:
a=np.random.randint(0,2,100000,np.int64)

In [0]:
head=0
tail=0
for item in a:
    if item==1:
        head+=1
    if item==0:
        tail+=1
print("Heads: ",head)
print("Tails: ",tail)

Heads:  50146
Tails:  49854


In [0]:
np.linspace(1,1000,49)

array([   1.    ,   21.8125,   42.625 ,   63.4375,   84.25  ,  105.0625,
        125.875 ,  146.6875,  167.5   ,  188.3125,  209.125 ,  229.9375,
        250.75  ,  271.5625,  292.375 ,  313.1875,  334.    ,  354.8125,
        375.625 ,  396.4375,  417.25  ,  438.0625,  458.875 ,  479.6875,
        500.5   ,  521.3125,  542.125 ,  562.9375,  583.75  ,  604.5625,
        625.375 ,  646.1875,  667.    ,  687.8125,  708.625 ,  729.4375,
        750.25  ,  771.0625,  791.875 ,  812.6875,  833.5   ,  854.3125,
        875.125 ,  895.9375,  916.75  ,  937.5625,  958.375 ,  979.1875,
       1000.    ])

In [0]:
np.linspace(1,1000,49,endpoint=False)

array([  1.        ,  21.3877551 ,  41.7755102 ,  62.16326531,
        82.55102041, 102.93877551, 123.32653061, 143.71428571,
       164.10204082, 184.48979592, 204.87755102, 225.26530612,
       245.65306122, 266.04081633, 286.42857143, 306.81632653,
       327.20408163, 347.59183673, 367.97959184, 388.36734694,
       408.75510204, 429.14285714, 449.53061224, 469.91836735,
       490.30612245, 510.69387755, 531.08163265, 551.46938776,
       571.85714286, 592.24489796, 612.63265306, 633.02040816,
       653.40816327, 673.79591837, 694.18367347, 714.57142857,
       734.95918367, 755.34693878, 775.73469388, 796.12244898,
       816.51020408, 836.89795918, 857.28571429, 877.67346939,
       898.06122449, 918.44897959, 938.83673469, 959.2244898 ,
       979.6122449 ])

In [0]:
int_ar=np.random.randint(1,12,(2,3,4))

In [0]:
int_ar[0]

array([[ 8,  6,  8,  5],
       [ 8, 11,  7,  4],
       [10,  1,  8, 10]])

In [0]:
int_ar[:,:,0:3]

array([[[ 8,  6,  8],
        [ 8, 11,  7],
        [10,  1,  8]],

       [[10,  4,  9],
        [ 7,  3,  6],
        [10,  8,  9]]])

In [0]:
int_ar

array([[[ 4, 10,  4,  6],
        [ 3,  2,  6,  2],
        [ 6,  6,  9,  4]],

       [[ 2,  6, 11,  5],
        [ 7,  7,  1,  6],
        [11, 10,  3,  7]]])

In [0]:
int_ar[int_ar==10]

array([10, 10])

In [0]:
int_ar[0,[0,2],:]

array([[ 4, 10,  4,  6],
       [ 6,  6,  9,  4]])

In [0]:
int_ar[0,:,(np.arange(2))]

array([[ 4,  3,  6],
       [10,  2,  6]])

# Numpy Operations

In [0]:
arr1=np.random.randint(5,75,(3,4))
arr2=np.random.randint(64,150,(3,4))

In [0]:
arr1

array([[64, 59, 36,  9],
       [67,  5, 46, 52],
       [55, 63, 49, 43]])

In [0]:
arr2

array([[ 68,  76, 120,  96],
       [ 93, 103,  66,  85],
       [145,  67, 102, 135]])

In [0]:
arr1+arr2

array([[132, 135, 156, 105],
       [160, 108, 112, 137],
       [200, 130, 151, 178]])

In [0]:
arr2%arr1

array([[ 4, 17, 12,  6],
       [26,  3, 20, 33],
       [35,  4,  4,  6]])

In [0]:
np.log(np.exp(arr1))

array([[64., 59., 36.,  9.],
       [67.,  5., 46., 52.],
       [55., 63., 49., 43.]])

In [0]:
np.log2(np.exp(arr2))

array([[ 98.10326278, 109.64482311, 173.12340491, 138.49872393],
       [134.1706388 , 148.59758921,  95.2178727 , 122.62907848],
       [209.19078093,  96.66056774, 147.15489417, 194.76383052]])

In [0]:
np.sqrt(arr2)

array([[ 8.24621125,  8.71779789, 10.95445115,  9.79795897],
       [ 9.64365076, 10.14889157,  8.1240384 ,  9.21954446],
       [12.04159458,  8.18535277, 10.09950494, 11.61895004]])

# Exercise

In [0]:
random_pts=np.random.rand(1000000,2)

In [0]:
%%time
inside=0
outside=0
for row in random_pts:
    if row[0]**2 + row[1]**2 < 1:
        inside+=1
    else:
        outside+=1
area_outside=outside/(inside+outside)
print(area_outside)

0.21434
CPU times: user 1.58 s, sys: 692 µs, total: 1.58 s
Wall time: 1.58 s


In [0]:
samplepts=10000000
dimensions=2
randompts=np.random.rand(samplepts,dimensions)

In [0]:
%%time
outside=0
dfo=np.zeros(samplepts)
for i in range(samplepts):
    for j in range(dimensions):
        dfo[i]+=randompts[i,j]**2
    if dfo[i]>1:
        outside+=1
print(outside/samplepts)


0.2147464
CPU times: user 25.3 s, sys: 51.6 ms, total: 25.4 s
Wall time: 25.4 s


In [0]:
def area_outside(sample_pts,dimensions):
    randompts=np.random.rand(sample_pts,dimensions)
    return np.sum(np.sqrt(np.sum(randompts*randompts,axis=1)) >1)/sample_pts

In [0]:
%%time
for i in range(2,11):
    print(i," :",area_outside(10000000,i))

2  : 0.2146449
3  : 0.4763488
4  : 0.6915444
5  : 0.8353272
6  : 0.9193192
7  : 0.963075
8  : 0.9841446
9  : 0.9935798
10  : 0.9975105
CPU times: user 7.26 s, sys: 11.6 ms, total: 7.27 s
Wall time: 7.27 s


In [0]:
%%time
print(6," :",area_outside(10000000,6))

6  : 0.9193395
CPU times: user 809 ms, sys: 1.92 ms, total: 811 ms
Wall time: 814 ms


# Broadcasting

In [0]:
arr1=np.arange(6)
print(arr1.T,"\n",
arr1.reshape(6,1),"\n",
arr1.reshape(1,6))

[0 1 2 3 4 5] 
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]] 
 [[0 1 2 3 4 5]]


In [0]:
arr2=np.arange(5)

In [0]:
arr1.reshape(6,1)+arr2

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8],
       [5, 6, 7, 8, 9]])

In [0]:
arr1.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [0]:
arr4=np.random.rand(3,4,2)

In [0]:
arr3.reshape(2,6)

array([[0.96513569, 0.14763229, 0.93668645, 0.51302722, 0.49662778,
        0.07371174],
       [0.14050765, 0.00817084, 0.87758517, 0.47488515, 0.52199215,
        0.18870105]])

In [0]:
arr1.reshape(6,1).T

array([[0, 1, 2, 3, 4, 5]])

In [0]:
arr4.T.shape

(2, 4, 3)

In [0]:
arr4.shape

(3, 4, 2)

In [0]:
arr4

array([[[0.63234516, 0.48562637],
        [0.46852122, 0.78383569],
        [0.14615324, 0.71121032],
        [0.08774961, 0.182336  ]],

       [[0.40023009, 0.01605261],
        [0.72616132, 0.37706605],
        [0.84961596, 0.99352786],
        [0.87677453, 0.187771  ]],

       [[0.03835524, 0.70320438],
        [0.57164369, 0.26363248],
        [0.3127395 , 0.50308316],
        [0.47946181, 0.36285266]]])

In [0]:
arr4.T

array([[[0.63234516, 0.40023009, 0.03835524],
        [0.46852122, 0.72616132, 0.57164369],
        [0.14615324, 0.84961596, 0.3127395 ],
        [0.08774961, 0.87677453, 0.47946181]],

       [[0.48562637, 0.01605261, 0.70320438],
        [0.78383569, 0.37706605, 0.26363248],
        [0.71121032, 0.99352786, 0.50308316],
        [0.182336  , 0.187771  , 0.36285266]]])

In [0]:
arr5=np.arange(1,101).reshape(5,5,4)
arr5+np.arange(5).reshape(5,1)


# File Handling

In [0]:
arr_planets_small=np.loadtxt("planets_small.txt",skiprows=1,usecols=tuple(range(1,10)))

In [0]:
arr_planets_small

array([[3.3000e-01, 4.8700e+00, 5.9700e+00, 6.4200e-01, 1.8980e+03,
        5.6800e+02, 8.6800e+01, 1.0200e+02, 1.4600e-02],
       [5.7900e+01, 1.0820e+02, 1.4960e+02, 2.2790e+02, 7.7860e+02,
        1.4335e+03, 2.8725e+03, 4.4951e+03, 5.9064e+03],
       [4.2226e+03, 2.8020e+03, 2.4000e+01, 2.4700e+01, 9.9000e+00,
        1.0700e+01, 1.7200e+01, 1.6100e+01, 1.5330e+02]])

In [0]:
arr_planets=np.genfromtxt("planets.txt",skip_header=1,usecols=tuple(range(1,10)))

In [0]:
arr_planets

array([[ 3.30000e-01,  4.87000e+00,  5.97000e+00,  7.30000e-02,
         6.42000e-01,  1.89800e+03,  5.68000e+02,  8.68000e+01,
         1.02000e+02],
       [ 4.87900e+03,  1.21040e+04,  1.27560e+04,  3.47500e+03,
         6.79200e+03,  1.42984e+05,  1.20536e+05,  5.11180e+04,
         4.95280e+04],
       [ 5.42700e+03,  5.24300e+03,  5.51400e+03,  3.34000e+03,
         3.93300e+03,  1.32600e+03,  6.87000e+02,  1.27100e+03,
         1.63800e+03],
       [ 3.70000e+00,  8.90000e+00,  9.80000e+00,  1.60000e+00,
         3.70000e+00,  2.31000e+01,  9.00000e+00,  8.70000e+00,
         1.10000e+01],
       [ 4.30000e+00,  1.04000e+01,  1.12000e+01,  2.40000e+00,
         5.00000e+00,  5.95000e+01,  3.55000e+01,  2.13000e+01,
         2.35000e+01],
       [ 1.40760e+03, -5.83250e+03,  2.39000e+01,  6.55700e+02,
         2.46000e+01,  9.90000e+00,  1.07000e+01, -1.72000e+01,
         1.61000e+01],
       [ 4.22260e+03,  2.80200e+03,  2.40000e+01,  7.08700e+02,
         2.47000e+01,  9.90000

In [0]:
np.isnan(arr_planets)

array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, 

In [0]:
arr_planets>5

In [0]:
arr_planets[np.isnan(arr_planets)]

array([], dtype=float64)

In [0]:
arr_planets[np.isnan(arr_planets)]=-1

In [0]:
np.savetxt("Planets Modified.txt",arr_planets, delimiter=",")

In [0]:
np.save("Planets_new",arr_planets)

In [0]:
!ls -lh

total 24K
-rw-r--r-- 1 root root 4.5K Jun 10 12:59 'Planets Modified.txt'
-rw-r--r-- 1 root root 1.6K Jun 10 13:01  Planets_new.npy
-rw-r--r-- 1 root root  254 Jun 10 12:50  planets_small.txt
-rw-r--r-- 1 root root 1.5K Jun 10 12:50  planets.txt
drwxr-xr-x 1 root root 4.0K May 29 18:19  sample_data


In [0]:
np.savez_compressed("Planetsss", arr1, arr2, arr4, arr_planets)

In [0]:
filez=np.load("Planetsss.npz")

In [0]:
filez

In [0]:
filez.files

['arr_0', 'arr_1', 'arr_2', 'arr_3']

In [0]:
filez['arr_1']

array([0, 1, 2, 3, 4])

# Stats

In [0]:
weight=np.random.randint(50,85,10000)
height=np.random.randint(150,180,10000)
age=np.random.randint(17,26,10000)

In [0]:
np.amax(weight)

84

In [0]:
np.histogram(height,range=(150,180))

(array([ 947, 1048,  965,  982,  976, 1010,  989, 1041, 1001, 1041]),
 array([150., 153., 156., 159., 162., 165., 168., 171., 174., 177., 180.]))

In [0]:
np.digitize(weight,bins=range(50,70,5))

array([4, 4, 3, ..., 4, 1, 4])

In [0]:
np.digitize(weight,bins=range(50,85,5))

array([4, 6, 3, ..., 6, 1, 4])

In [0]:
list(range(50,85,5))

[50, 55, 60, 65, 70, 75, 80]

In [0]:
randin=np.random.randint(10,21,20)

In [0]:
randin

array([13, 17, 15, 15, 17, 15, 13, 10, 12, 17, 18, 15, 20, 17, 13, 13, 11,
       10, 18, 20])

In [0]:
np.histogram(randin, bins=5)

(array([3, 5, 4, 4, 4]), array([10., 12., 14., 16., 18., 20.]))

In [0]:
np.digitize(randin,(10,12,14,16,18,20),right=True)

array([2, 4, 3, 3, 4, 3, 2, 0, 1, 4, 4, 3, 5, 4, 2, 2, 1, 0, 4, 5])

In [0]:
np.digitize(randin,(10,12,14,16,18,20))

array([2, 4, 3, 3, 4, 3, 2, 1, 2, 4, 5, 3, 6, 4, 2, 2, 1, 1, 5, 6])

In [0]:
np.digitize(randin,(10,12,14,16,18),right=True)

array([2, 4, 3, 3, 4, 3, 2, 0, 1, 4, 4, 3, 5, 4, 2, 2, 1, 0, 4, 5])

In [0]:
np.digitize(randin,(10,12,14,16,18))

array([2, 4, 3, 3, 4, 3, 2, 1, 2, 4, 5, 3, 5, 4, 2, 2, 1, 1, 5, 5])

In [0]:
np.digitize(randin,(12,14,16,18,20))

array([1, 3, 2, 2, 3, 2, 1, 0, 1, 3, 4, 2, 5, 3, 1, 1, 0, 0, 4, 5])

In [4]:
total=np.concatenate((weight.reshape(1,10000),height.reshape(1,10000),age.reshape(1,10000)))
total

array([[ 72,  61,  81, ...,  74,  81,  82],
       [174, 154, 179, ..., 156, 153, 173],
       [ 17,  20,  18, ...,  21,  21,  24]])

In [0]:
np.vstack((weight, height, age))

array([[ 66,  78,  64, ...,  78,  53,  65],
       [155, 151, 177, ..., 174, 163, 176],
       [ 22,  21,  17, ...,  21,  19,  24]])

In [0]:
np.amin(total,axis=0)

array([22, 21, 17, ..., 21, 19, 24])

In [0]:
np.amin(total,axis=1)

array([ 50, 150,  17])

In [0]:
normalised_total=(total-np.mean(total,axis=1).reshape(3,1))/np.std(total,axis=1).reshape(3,1)

In [14]:
np.mean(normalised_total,axis=1)

array([6.70041800e-16, 1.22355459e-15, 1.95399252e-16])

In [21]:
np.mean(total,axis=1).reshape(3,1)

array([[ 67.07  ],
       [164.5461],
       [ 21.0722]])

In [10]:
total

array([[ 59,  50,  76, ...,  54,  58,  64],
       [157, 178, 162, ..., 155, 158, 154],
       [ 23,  17,  21, ...,  18,  23,  20]])

In [19]:
np.round(np.mean(normalised_total,axis=1),10)


array([0., 0., 0.])

In [0]:
test=np.random.rand(100)

In [21]:
np.mean(test)

0.4314212268337294

In [22]:
np.median(test)

0.4035904791270886

In [10]:
np.cumsum(total, axis=1)

array([[     72,     133,     214, ...,  670537,  670618,  670700],
       [    174,     328,     507, ..., 1645135, 1645288, 1645461],
       [     17,      37,      55, ...,  210677,  210698,  210722]])

In [8]:
total.shape

(3, 10000)

In [20]:
np.cumsum(total,axis=1)/np.arange(1,10001).reshape(1,10000)

array([[ 72.        ,  66.5       ,  71.33333333, ...,  67.06711342,
         67.06850685,  67.07      ],
       [174.        , 164.        , 169.        , ..., 164.54640928,
        164.54525453, 164.5461    ],
       [ 17.        ,  18.5       ,  18.33333333, ...,  21.07191438,
         21.07190719,  21.0722    ]])

In [9]:
total

array([[ 72,  61,  81, ...,  74,  81,  82],
       [174, 154, 179, ..., 156, 153, 173],
       [ 17,  20,  18, ...,  21,  21,  24]])

In [0]:
time=np.arange(1,10001)

In [0]:
time.resize(1,10000)

In [30]:
time.size

10000

# Case Study

In [0]:
cric_arr = np.genfromtxt("cric_data.tsv",skip_header=1,)

In [0]:
cric_tp=cric_arr.T

In [4]:
np.mean(cric_tp,1)

array([112.        ,  39.87555556,  32.06222222, 220.79555556])

In [64]:
np.median(cric_tp,1)

array([112.,  27.,  22., 216.])

In [72]:
quartiles_all = np.percentile(cric_tp,[25,50,75],axis=1).T
IQRs=np.array(quartiles_all[1:4,2]-quartiles_all[1:4,0])
print(IQRs)

[57. 46. 98.]


In [6]:
np.histogram(cric_tp[1])

(array([99, 36, 28, 16, 11, 17,  8,  8,  1,  1]),
 array([  0. ,  18.6,  37.2,  55.8,  74.4,  93. , 111.6, 130.2, 148.8,
        167.4, 186. ]))

In [13]:
for i in range(0,len(cric_tp[1]),25):
    print(np.mean(cric_tp[1,i:i+25]))

33.96
49.4
38.48
40.16
39.36
38.2
44.6
39.52
35.2


In [83]:
np.mean(cric_tp[1].reshape(int(cric_tp[1].size/25),25),axis=1)

array([33.96, 49.4 , 38.48, 40.16, 39.36, 38.2 , 44.6 , 39.52, 35.2 ])

In [17]:
np.mean(cric_tp[1][cric_tp[1]>=100])

125.0

In [19]:
cric_tp[1][cric_tp[1]>=100]

array([100., 104., 138., 141., 186., 146., 141., 123., 120., 122., 100.,
       152., 105., 122., 100., 117., 141., 139., 114., 127., 110., 146.,
       101., 140., 113., 102.])

In [23]:
(cric_tp[1,220:250])

array([ 25., 102.,   0.,  27.,  40.])

In [24]:
np.mean(cric_tp[1][cric_tp[2]<10])

40.74285714285714

In [25]:
cric_tp[1][cric_tp[2]<10]

array([ 37.,  14.,   4.,   0.,  62.,  38.,  65.,   0.,  48.,  62.,  27.,
        27.,  51.,  18.,  65.,  28.,   2.,  54.,   4.,  14., 100.,  57.,
         0.,   5.,   0.,  30.,  83.,  93.,   0., 152.,   0.,   1.,  53.,
         0.,  81.,  78., 122.,   9.,  13.,  36.,  29.,  12.,  34., 100.,
        44.,  82.,   0.,   6.,  49.,  64.,  43.,  72.,  44.,  47.,  17.,
        35.,  88.,   0.,  33., 110., 146.,   7.,  11.,  94.,  55.,   0.,
        28.,   2.,  27.,  40.])

In [0]:
better_player = cric_tp[1]>cric_tp[2]
better_player=better_player*1
better_player=better_player.astype(str)
better_player[better_player=="1"] = "Sachin"
better_player[better_player=="0"] = "Rahul"
better_player

In [0]:
def avg_score_after(Numpy_array_of_player,n):
    return np.mean(Numpy_array_of_player[Numpy_array_of_player>=n])-n

In [101]:
avg_score_after(cric_tp[1],60)

38.67213114754098

In [0]:
np.where(cric_tp[1]>cric_tp[2],"Sachin","Rahul")

In [102]:
np.histogram(np.cumsum(cric_tp[1]),np.arange(0,10000,1000))

(array([29, 18, 26, 25, 26, 26, 23, 22, 30]),
 array([   0, 1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000]))

In [53]:
a = np.array([[1,2,3,], [4,5,6]])
print(a[1,2])

6


In [57]:
a = np.array([1,2,3,4,5])
print(a[::-1])

[5 4 3 2 1]


In [63]:
a[4:0:-1]

array([5, 4, 3, 2])

In [0]:
quartiles_india = np.percentile(cric_tp[3],[25,50,75,100])

In [87]:
quartiles_india

array([175., 216., 273., 499.])

In [92]:
np.mean(cric_tp[1][cric_tp[3]<quartiles_india[2]])

28.18018018018018

In [95]:
for i in range(4):
    if i==0:
        print(np.mean(cric_tp[1][(cric_tp[3]<quartiles_india[i])]))
    else:
        print(np.mean(cric_tp[1][(cric_tp[3]<quartiles_india[i]) & (cric_tp[3]>quartiles_india[i-1])]))

19.672727272727272
35.851851851851855
39.55555555555556
63.49090909090909


In [97]:
np.array([1,2,3,4])-np.array([3,4,5,6])

array([-2, -2, -2, -2])

In [98]:
np.setdiff1d(np.array([1,2,3,4]),np.array([3,4,5,6]))

array([1, 2])

In [100]:
cric_tp.shape[0]

4